name: "Run android build"

on:
  push:
    branches:
      - master
    paths: 
      - apps/mobile
      - .github/workflows/android.yml
concurrency:
  group: ${ GIT_BRANCH_NAME }
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning current repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_PAT }}

      - name: Clone credentials
        uses: actions/checkout@v2
        with:
          repository: codeleap-uk/keystores-android
          ref: ${{ secrets.REPOSITORY_BRANCH }}
          token: ${{ secrets.GH_PAT }}
          path: keystores-android

      - name: Move credentials to apps/mobile/android/app/keystores
        run: |
          mv keystores-android/* apps/mobile/android/app/keystores
      
      - name: Set up node
        uses: actions/setup-node@v3
        with: 
          node-version: 18.15.0
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn
          yarn build

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'liberica'
          java-version: '11'
          cache: 'gradle'

      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1
      
      - name: New internal version
        run: |
          cd apps/mobile/android/fastlane
          fastlane internal

      - name: Commit version file
        if: always()
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          cd apps/mobile
          git restore android/app/version.json
          git pull
          git checkout master
          git pull origin master
          cd android/fastlane
          fastlane increment_version_code
          cd ../..
          git add app/version.json
          git diff-index --quiet HEAD || git commit -m "Update version.json"
          git push origin master

