name: "Run android build"

on:
  push:
    branches:
      - master
    paths: 
      - apps/mobile
      - .github/workflows/android.yml
concurrency:
  group: android-${ GIT_BRANCH_NAME }
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning current repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_PAT }}

      - name: Clean Disk
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: false
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: true

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adoptopenjdk'
          java-version: '17'
          cache: 'false'

      - uses: oven-sh/setup-bun@v2

      - name: Clone credentials
        uses: actions/checkout@v2
        with:
          repository: codeleap-uk/keystores-android
          ref: ${{ secrets.REPOSITORY_BRANCH }}
          token: ${{ secrets.GH_PAT }}
          path: keystores-android

      - name: Move credentials to apps/mobile/android/app/keystores
        run: |
          mv keystores-android/* apps/mobile/android/app/keystores

      - name: Install dependencies
        run: |
          bun install
          bun install -g turbo

      - name: Build libraries
        run: |
          bun run build

      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1

      - name: Get latest google play version
        run: |
          pip install codemagic-cli-tools
          pip3 install pyOpenSSL==24.2.1 --upgrade

          echo "update version code"

          export GPLAY=$(google-play get-latest-build-number --package-name uk.co.codeleap.template --credentials @file:apps/mobile/android/app/keystores/playstore-credentials.json)
          
          bun mobile updatePlayStoreVersion $GPLAY
          cat apps/mobile/android/app/version.json
      
      - name: New internal version
        run: |
          cd apps/mobile/android/fastlane
          fastlane internal
