name: "Run android build"

on:
  push:
    branches:
      - master
    paths: 
      - apps/mobile
      - .github/workflows/android.yml
concurrency:
  group: android-${ GIT_BRANCH_NAME }
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning current repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_PAT }}

      - name: Clone credentials
        uses: actions/checkout@v2
        with:
          repository: codeleap-uk/keystores-android
          ref: ${{ secrets.REPOSITORY_BRANCH }}
          token: ${{ secrets.GH_PAT }}
          path: keystores-android

      - name: Move credentials to apps/mobile/android/app/keystores
        run: |
          mv keystores-android/* apps/mobile/android/app/keystores
      
      - name: Set up node
        uses: actions/setup-node@v3
        with: 
          node-version: 18.15.0
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn
          yarn global add turbo

      - name: Build libraries
        run: |
          yarn build

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1

      - name: Get latest google play version
        run: |
          pip install codemagic-cli-tools
          pip3 install pyOpenSSL --upgrade

          echo "update version code"

          export GPLAY=$(google-play get-latest-build-number --package-name uk.co.codeleap.template --credentials @file:apps/mobile/android/app/keystores/playstore-credentials.json)
          
          yarn mobile updatePlayStoreVersion $GPLAY
          cat apps/mobile/android/app/version.json
      
      - name: New internal version
        run: |
          cd apps/mobile/android/fastlane
          fastlane internal
