name: Documentation deployment
on:
  push:
    branches:
      - master
    paths: 
      - apps/docs/package.json
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: ⏬ Cloning current repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      - name: 🔐 Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-2

      - name: Version update detected
        run: |
          yarn install
          yarn build
          yarn docs build-web
          yarn docs deploy
