name: Documentation deployment
on:
  push:
    branches:
      - master
    paths: 
      - apps/docs/package.json
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: ⏬ Cloning current repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.16.1'

      - name: 🛠 Set up Python 3.6 (needed for eb cli)
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      
      - name: 🔐 Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-2

      # - name: 🔐 Add profile credentials to ~/.aws/credentials
      #   env:
      #       AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      #       AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      #   run: |
      #       aws configure set aws_access_key_id $AWS_ACCESS_KEY
      #       aws configure set aws_secret_access_key $AWS_SECRET_KEY

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-name: ./apps/docs/package.json

      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
        run: 
          yarn install
          yarn build
          yarn docs build-web
          yarn docs deploy
