name: Test build
on:   
  pull_request:
    branches: 
      - master
    paths:
      - "packages/**/*"
concurrency:
  group: pr-${ GIT_BRANCH_NAME }
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone current repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_PAT }}
          
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.23

      - name: Install dependencies
        run: |
          bun install
          bun install -g turbo

      - name: Build libraries
        run: |
          bun run build
      
