name: Publish libraries
on:
  push:
    branches:
      - publish
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: ⏬ Cloning current repo
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.1'

      - name: Install dependencies
        run: |
          yarn install

      - name: Build libraries
        run: |
          yarn build
      
      - name: Build libraries
        run: |
          yarn common version --patch
          yarn p:mobile version --patch
          yarn p:web version --patch

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/common/package.json
          dry-run: true
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/mobile/package.json
          dry-run: true
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/web/package.json
          dry-run: true
