name: Publish libraries
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone current repo
        uses: actions/checkout@v2

      - name: Get Yarn cache path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      
      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.1'
      
      - name: Load Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          yarn install

      - name: Build libraries
        run: |
          yarn build

      - name: Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Version bump
        run: |
          yarn config set version-git-tag false
          yarn config set npmAuthToken ${{ secrets.NPM_TOKEN }}
          yarn common publish --patch
          yarn p:mobile publish --patch
          yarn p:web publish --patch

     

      - name: Git push
        run: |
          git push origin master
