name: Publish libraries
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone current repo
        uses: actions/checkout@v2

    
      - uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'


      - name: Install dependencies
        run: |
          yarn

      - name: Build libraries
        run: |
          yarn build

      - name: Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Publish
        run: ${PWD}/publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Git push
        if: always()
        run: |
          git add packages/*/package.json 
          git commit -m "Version bump"
          git push origin master
