name: Publish libraries
on:
  push:
    branches:
      - master
    paths:
      - "packages/**/*"
      - .github/workflows/publish.yml
concurrency:
  group: publish-${ GIT_BRANCH_NAME }
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone current repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_PAT }}

  
      - uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'


      - name: Install dependencies
        run: |
          yarn

      - name: Install Turbo
        run: |
          yarn global add turbo
          
      - name: Build libraries
        run: |
          yarn build

      - name: Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Publish
        run: |
          chmod +x ./publish.sh
          ./publish.sh
          yarn notifyVersion
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }} 
