name: Publish libraries
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone current repo
        uses: actions/checkout@v2

    
      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.1'
      

      - name: Install dependencies
        run: |
          yarn --prefer-offline

      - name: Build libraries
        run: |
          yarn build

      - name: Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Version bump
        run: |
          cd packages/common
          npm version patch
          npm publish
          cd ../..
          cd packages/mobile
          npm version patch
          npm publish
          cd ../..
          cd packages/web
          npm version patch
          npm publish

        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


      - name: Git push
        if: always()
        run: |
          git push origin master
