name: Publish libraries
on:
  push:
    branches:
      - publish
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone current repo
        uses: actions/checkout@v2

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

    
      - uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'


      - name: Install dependencies
        run: |
          yarn

      - name: Build libraries
        run: |
          yarn build

      - name: Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Publish
        run: |
          chmod +x ./publish.sh
          ./publish.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Git push
        if: always()
        run: |
          git pull
          git checkout master

          git add packages/*/package.json 
          git commit -m "Version bump"
          
          git push origin master
