name: Publish libraries
on:
  push:
    branches:
      - master
    paths:
      - "packages/**/*"
      - .github/workflows/publish.yml

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone current repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_PAT }}

  
      - uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'


      - name: Install dependencies
        run: |
          yarn
      - name: Build libraries
        run: |
          yarn build

      - name: Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Publish
        run: |
          yarn release
          chmod +x ./publish.sh
          ./publish.sh
          yarn notifyVersion
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }} 

      - name: Git push
        if: always()
        run: |
          git pull
          git restore **/**
          git add packages
          git commit -m "update package versions"
          git push --follow-tags origin master
