name: Publish libraries
on:
  push:
    branches:
      - master
    paths:
      - "packages/**/package.json"
      - .github/workflows/publish.yml
concurrency:
  group: publish-${ GIT_BRANCH_NAME }
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone current repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.GH_PAT }}
      
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          bun install

      - name: Install Turbo
        run: |
          bun install -g turbo
          
      - name: Build libraries
        run: |
          bun run build

      - name: Run Tests
        run: |
          bun test

      - name: Git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Publish
        run: |
          chmod +x ./publish.sh
          ./publish.sh ${{ secrets.NPM_TOKEN }}
          bun run notifyVersion
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }} 
